title:            Liucheng Xu
description:      It is our light, not our darkness that frightens us.
url:              # Site url.
disqus_shortname: xuliuchengxlc  # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: UA-73260325-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://xuliuchengxlc.github.io
  - name:         Email
    url:          mailto:xuliuchengxlc@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/xuliuchengxlc
    external:     true

kramdown:
  input:    GFM
  syntax_highlighter:    rouge

defaults:
    -
        scope:
            path:    "_posts"
            type:    "posts"
        values:
          layout:    "post"
          disqus:    "y"
          author:    "Liucheng Xu"
