title:            Liucheng Xu
description:      It is our light, not our darkness that frightens us.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: xuliuchengxlc  # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://xuliuchengxlc.github.io
    external:     true
  - name:         Email
    url:          mailto:xuliuchengxlc@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/xuliuchengxlc
    external:     true
  - name:         Weibo
    url:          http://weibo.com/3168860973/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1 
    external:     true 
  - name:         Zhihu
    url:          https://www.zhihu.com/people/simple_the_best
    external:     true
highlighter:      rouge
markdown:         kramdown
kramdown:
  input:    GFM
  auto_ids:    true
  auto_id_prefix:    'id-'
